version: "3"

services:
  kamailio:
    image: kamailio/kamailio-ci:5.5.2
    hostname: kamailio
    restart: always
    volumes:
      - ./etc/kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
      - ./etc/kamailio/kamctlrc:/etc/kamailio/kamctlrc
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "7722:7722"
    depends_on:
      - mysql

  coturn:
    image: coturn/coturn:latest
    hostname: coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-49200:49152-49200/udp"
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    hostname: mysql-kamailio
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kamailio

